### ISSUE TITLE
Give a link to online service?

### ISSUE THREAD

**Issue by ivan-kleshnin** [ohanhi/hyperscript-helpers#20]
Hello! I've made a [library](https://github.com/ivan-kleshnin/html-to-hyperscript) and a [webservice](https://github.com/Paqmind/html-to-hyperscript) to convert HTML to HyperScript-Helpers.
Webservice is hosted here: http://html-to-hyperscript.paqmind.com/
Manual conversions of HTML to HS turned out to be very boresome.

I'd like to leave a link to it in README. A bit of self-marketing, but I think it may be useful for other people. Would you accept such PR?

**Comment by ohanhi** [comment]
Sure, seems like a useful tool.
