### ISSUE TITLE
Using ES2015 Proxy 

### ISSUE THREAD

**Issue by TylorS** [ohanhi/hyperscript-helpers#26]
I was experimenting with ES2015 Proxy and it seemed like a good fit for this library depending on the target audience or simply in the future when there is more browser support.
Basically it just relieves the need to keep a list of TAG_NAMES or to build an object yourself.
In particular this works really nicely because with snabbdom (the h() I generally use) svg 'just works' there is no separate svg() function like there is for virtual-dom. 

Feel free to close this as this isn't really an issue, but I thought you may be interested.

``` js
const isValidString =
  param =>
    typeof param === 'string' && param.length > 0;

const startsWith =
  (string, start) =>
    string[0] === start;

const isSelector =
  param =>
    isValidString(param) && 
    startsWith(param, '.') || 
    startsWith(param, '#');

const hh = 
  h => 
    new Proxy(h, {
      get(target, property) {
        return (first, ...rest) => {
          if (isSelector(first)) {
            return h(property + first, ...rest);
          } else {
            return h(property, first, ...rest);
          }
        }
      }
    });

// usage
import h from 'snabbdom/h'
const {div, main, svg, g, circle} = hh(h)
...
```

**Comment by TylorS** [comment]
Quick example
http://esnextb.in/?gist=5b841ef982b0ec819595

**Comment by Cmdv** [comment]
This would be a good addition

**Comment by ohanhi** [comment]
Agreed, this would be really nice. Sadly Proxies only work in [Edge, Firefox and Chrome Beta](http://caniuse.com/#feat=proxy) at the moment, so using them is not really an option within the next year or so. They are one of the things that are [impossible to polyfill properly](https://www.npmjs.com/package/babel-plugin-proxy#motivation).

**Comment by TylorS** [comment]
No worries. It was just for experimentation anyways. Closing this after seeing its impossible to polyfill.
