### ISSUE TITLE
Hyperscript helper with no parameter bug?

### ISSUE THREAD

**Issue by arlair** [ohanhi/hyperscript-helpers#30]
I created a bug over https://github.com/TylorS/cycle-snabbdom/issues/27
but I think the issue might be in Hyperscript Helpers.

When I defined a helper with no parameters, eg a div(), or a br(), it is calling h as:

```
h(tagname, undefined)
```

Snabbdom seems to expect

```
h(tagname)
```

which also seems logical to me.

I'm not sure what virtual-dom expects.

Do you think this is a bug?

**Comment by arlair** [comment]
relevant piece of code is here:
https://github.com/ohanhi/hyperscript-helpers/blob/master/src/index.js#L20

**Comment by arlair** [comment]
relevant piece of code in Snabbdom is here where it defines defaults and overrides based on how many parameters are passed.

https://github.com/paldepind/snabbdom/blob/034d8820a2925fba11731d1e288d4ff19f5cd72f/h.js#L14

**Comment by ohanhi** [comment]
@arlair Your fix is now published:

``` bash
hyperscript-helpers (master)› npm publish
+ hyperscript-helpers@2.1.1
```
