### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ivan-kleshnin** [ohanhi/hyperscript-helpers#34]
Since 3.0.0 I'm getting `_htmlTagNames2.default.forEach is not a function` 
(checked within non ES2016 environment).

That's because of mismatch between CommonJS and SystemJS(?) module systems

1) **html-tag-names/index.js**

`module.exports = require('./index.json');`

2) **hyperscript-helpers/src/index.js**

`import tagNames from 'html-tag-names';`

3) **Generated code**

``` js
var _htmlTagNames = require('html-tag-names');

var _htmlTagNames2 = _interopRequireDefault(_htmlTagNames);

...

exports['default'] = function (h) {
  var createTag = node(h);
  var exported = { tagNames: _htmlTagNames2['default'], isSelector: isSelector, createTag: createTag };
  _htmlTagNames2['default'].forEach(function (n) { // <-- `default` is undefined
    exported[n] = createTag(n);
  });
  return exported;
};
```

**Comment by arty-name** [comment]
I have a similar issue in ES6 environment: `_htmlTagNames2['default']` is defined, but it is an empty object

**Comment by tusharmath** [comment]
Facing the same issue. Is there a workaround for the time being?

**Comment by ohanhi** [comment]
Sorry for the hold-up folks, I was on summer holidays and this was not an easy nut to crack. However, I circumvented the problem now as per #36, and version 3.0.1 should now be published with this fix. 🌞
