### ISSUE TITLE
Support for path, line, g, circle within svg's

### ISSUE THREAD

**Issue by peterszerzo** [ohanhi/hyperscript-helpers#37]
Maybe I'm misunderstanding the earlier SVG conversation, but if it's appropriate, I'd really like support for these tags. Happy to make a PR if it makes sense :).

**Comment by peterszerzo** [comment]
I tried to create a pull request, but when I go through the steps listed under `## Contributing`, `npm run commit` isn't doing anything. Any idea what's going on?

**Comment by ohanhi** [comment]
@pickled-plugins It should basically bring up a "CLI wizard" for formatting commit messages nicely. In essence, you can bypass that and use a format similar to the following yourself:

```
feat: add most common svg tags
```

This is a new feature, hence the `feat:`. The commit message itself should be imperative tense, with all small letters.

Thanks!

**Comment by peterszerzo** [comment]
I went through the wizard, but the commit itself didn't run when I was finished (changed files were still in staging). Have you encountered this before, @ohanhi?

I'll just do it manually then. Thank you!

**Comment by MelleB** [comment]
Please see #39

**Comment by peterszerzo** [comment]
Cool - sorry, folks, had a commit ready a while back, but forgot about it :/.
