### ISSUE TITLE
tagName(children) is not working with React 

### ISSUE THREAD

**Issue by jas-chen** [ohanhi/hyperscript-helpers#38]
Hi,

Following code is not working:

``` javascript
const React = require('react');
const ReactDom = require('react-dom');
const { p } = require('hyperscript-helpers')(React.createElement);

ReactDom.render(p(['test']), document.getElementById('root'));
```

Error:

```
Warning: Unknown prop `0` on <p> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop in p
```

My setup:
"hyperscript-helpers": "^3.0.1",
"react": "^15.3.2",
"react-dom": "^15.3.2",

**Comment by ohanhi** [comment]
Hi @jas-chen,

Thank you for reporting. `React.createElement` is sadly not fully compliant with the hyperscript "standard" pattern. It requires the child list to be the third argument. [See docs](https://facebook.github.io/react/docs/react-api.html#createelement). A nice solution to this inconvenience is to use e.g. [react-hyperscript](https://github.com/mlmorg/react-hyperscript).

Does this solve the issue for you?

**Comment by jas-chen** [comment]
Thanks, I got it. Why not add a line to README so people like me can avoid trying to use it?

**Comment by ohanhi** [comment]
That's a good idea, I will!

**Comment by ohanhi** [comment]
Just a heads-up, I added a "preferred" React section here: https://github.com/ohanhi/hyperscript-helpers#how-to-use

It's on npm as version 3.0.2.
