### ISSUE TITLE
attribute 'class' seem doesn't work correctly with Cycle js

### ISSUE THREAD

**Issue by olivmonnier** [ohanhi/hyperscript-helpers#4]
i recommend to use 'className' instead of 'class'

**Comment by ohanhi** [comment]
@staltz Could you verify?

**Comment by ohanhi** [comment]
Actually, @Oliv75, won't you try to simply use `'className'`? This library is in essence a proxy to the given hyperscript implementation, so whatever works on the hyperscript library should work through `hyperscript-helpers` too.

**Comment by ohanhi** [comment]
Okay, I can confirm that everything works as expected when you simply use `className` instead of `class` in Cycle. Closing the issue.
/cc @Oliv75 @staltz
