### ISSUE TITLE
svg issues using 'xlink:href'

### ISSUE THREAD

**Issue by iambumblehead** [ohanhi/hyperscript-helpers#41]
I'm using svg symbols and am finding it necessary to use the innerHTML attribute.

This **does result in svg render** but requires innerHTML:
```javascript
div('.mydiv', {
  innerHTML : [
    '<svg>',
    '  <use xlink:href="./symbols.sprite.svg#ic_perm_data_setting_24px"></use>',
    '</svg>'
  ].join('\n')
})      
```

This **does not render the 'xlink:href'** attribute to the use element:
```javascript
svg('.mysvg', [
  use('.myuse', {
     'xlink:href' : './symbols.sprite.svg#ic_perm_data_setting_24px'
  })
])
```

These **do render attribute 'xlink:href'** to the use element, but **do not result in svg render**:
```javascript
svg('.mysvg', [
  use('.myuse', {
    attributes : {
      'xlink:href' : './symbols.sprite.svg#ic_perm_data_setting_24px'
    }
  })
])
```

```javascript
svg('.mysvg', {
  innerHTML : '<use xlink:href="./symbols.sprite.svg#ic_perm_data_setting_24px"></use>'
})
```

**Comment by iambumblehead** [comment]
[this](https://github.com/Matt-Esch/virtual-dom/issues/262) seems related, but after removing the class/id string from the svg and use elements I still do not see rendered svg image.

**Comment by ohanhi** [comment]
I think this is out of the scope of hyperscript-helpers and more to do with the actual hyperscript and/or virtual-dom implementation being used. After all, hyperscript-helpers is just a collection of functions that pass the arguments directly to the hyperscript library being used.
