### ISSUE TITLE
please export tag names

### ISSUE THREAD

**Issue by iambumblehead** [ohanhi/hyperscript-helpers#42]
please export tag names.

This way my script may reuse tag names you've defined --currently my script must define its own tags, and it uses a copy/pasted definition from your sources here.

**Comment by ohanhi** [comment]
IIRC, they exported as `TAG_NAMES` in the default export. Could you verify?

**Comment by iambumblehead** [comment]
I see they are exported with the object returned by calling the helpers function. I can restructure my own script to access that definition instead.
