### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by tomek-he-him** [ohanhi/hyperscript-helpers#5]
Would be cool. I’m just wondering whether to submit a PR here or make a new package of it.

It looks like [SVG support in _virtual-dom_](https://github.com/Matt-Esch/virtual-dom/blob/903d884a8e4f05f303ec6f2b920a3b5237cf8b92/virtual-hyperscript/svg.js) is/used to be a separate module in the same package. I don’t quite get the logic of their file structure though.

**Comment by ohanhi** [comment]
Sure! I think a separately `require`d module would be great.

**Comment by tomek-he-him** [comment]
You mean like `require('hyperscript-helpers/svg')` (in this package) or `require('hyperscript-helpers-svg')` (another project)?

I guess the first option is easier to manage and discover. Perhaps we could eventually have `hyperscript-helpers/html`, `hyperscript-helpers/svg` and `hyperscript-helpers/mathml` – and `require('hyperscript-helpers')` would ship all of them?

Breaking API changes – if they are ever to come – would come in all three submodules simultanously. I guess in this case it may make no sense to [release and version these separately](https://github.com/mattdesl/module-best-practices/pull/2#issuecomment-121116887).

**Comment by ohanhi** [comment]
This package is fine in my opinion. Regarding API changes, I do have an idea about making classnames easier to add, but it would likely be an optional variant so a _minor_ change.

**Comment by tomek-he-him** [comment]
:+1: I’ll make it a separate package then. When the time comes :)
