### ISSUE TITLE
input function attributes does not take in "list"

### ISSUE THREAD

**Issue by chandru89new** [ohanhi/hyperscript-helpers#52]
** Description of the issue **
The input function does not use/respect the `list` attribute if given. In render, it drops that attribute. This makes it impossible to use the `datalist` feature through an `input` tag.

** Reproduce **
https://codesandbox.io/s/zealous-nightingale-kobop

** Expected behavior **
During render, `input` should use the `list` attribute given to it.

**Comment by ohanhi** [comment]
This issue seems to be in `hyperscript`, not `hyperscript-helpers`. The following code seems to work just as poorly as your example:

```js
import "./styles.css";
import h from "hyperscript";

document
  .getElementById("app")
  .appendChild(
    h("div", [
      h("input", { list: "countries" }),
      h("datalist#countries", [
        h("option", { value: "USA" }),
        h("option", { value: "India" })
      ])
    ])
  );
```

**Comment by chandru89new** [comment]
Thank you. Apologies for not checking this further before raising the bug. I'll close this.
